#!/bin/bash

##############################################################################
#Copyright HuaCloud Inc.
# This program isn't  free software: but you can redistribute it and/or modify
# it when you deploy Huacloud iaas product for 1230 version.
###########################################################################
#
:<<!EOF!
function illustration{
查看CPU信息,分为当前及15分钟平均值 
}
!EOF!

#set -e
#set	-o xtrace
temp_dir=`mktemp`; rm -rf $temp_dir; mkdir -p $temp_dir
TOPDIR=$(cd $(dirname "$0") && pwd)

function cpuuse() {
#监控系统负载与CPU、内存、硬盘、登录用户数，

# 1、监控系统负载的变化情况，超出时发告警：

#抓取cpu的总核数
cpu_num=`grep -c 'model name' /proc/cpuinfo`
echo “cpu总核数$cpu_num
#抓取当前系统15分钟的平均负载值
load_15=`uptime | awk '{print $13}'`
echo "当前系统15分钟的平均负载值$load_15"
#计算当前系统单个核心15分钟的平均负载值，结果小于1.0时前面个位数补0。
average_load=`echo "scale=2;a=$load_15/$cpu_num;if(length(a)==scale(a)) print 0;print a" | bc`
echo "系统单个核心15分钟的平均负载值$average_load"
#取上面平均负载值的个位整数
average_int=`echo $average_load | cut -f 1 -d "."`

#设置系统单个核心15分钟的平均负载的告警值为0.70(即使用超过70%的时候告警)。
load_warn=0.70
echo "设置系统单个核心15分钟的平均负载的告警值" 70

#当单个核心15分钟的平均负载值大于等于1.0（即个位整数大于0） ，直接发告警；如果小于1.0则进行二次比较
if [[ $average_int > 0 ]] ; then
echo "$IP服务器15分钟的系统平均负载为$average_load，超过警戒值1.0，请立即处理！！！" 
else

#当前系统15分钟平均负载值与告警值进行比较（当大于告警值0.70时会返回1，小于时会返回0 ）
load_now=`expr $average_load \> $load_warn`

#如果系统单个核心15分钟的平均负载值大于告警值0.70（返回值为1），则发告警
if (($load_now == 1)); then
echo "$IP服务器15分钟的系统平均负载达到 $average_load，超过警戒值0.70，请及时处理。" 
fi

fi

# 2、监控系统cpu的情况，当使用超过80%的时候发告警：

#取当前空闲cpu百份比值（只取整数部分）
cpu_idle=`top -b -n 1 | grep Cpu | awk '{print $8}' | cut -f 1 -d "."`

#设置空闲cpu的告警值为20%，如果当前cpu使用超过80%（即剩余小于20%），立即发告警
if (($cpu_idle < 20)); then
echo "$IP服务器cpu剩余$cpu_idle%，使用率已经超过80%，请及时处理。" 
fi

# 3、监控系统交换分区swap的情况，当使用超过80%的时候发告警：

#系统分配的交换分区总量
swap_total=`free -m | grep Swap | awk '{print $2}'`
echo "系统分配的交换分区总量$swap_total"
#当前剩余的交换分区free大小
swap_free=`free -m | grep Swap | awk '{print $4}'`
echo "当前剩余的交换分区free大$swap_free"
#当前已使用的交换分区used大小
swap_used=`free -m | grep Swap | awk '{print $3}'`
echo "当前已使用的交换分区used大小$swap_used"
if (($swap_used != 0)); then
#如果交换分区已被使用，则计算当前剩余交换分区free所占总量的百分比，用小数来表示，要在小数点前面补一个整数位0
swap_per=0`echo "scale=2;$swap_free/$swap_total" | bc`

#设置交换分区的告警值为20%(即使用超过80%的时候告警)。
swap_warn=0.20

#当前剩余交换分区百分比与告警值进行比较（当大于告警值(即剩余20%以上)时会返回1，小于(即剩余不足20%)时会返回0 ）
swap_now=`expr $swap_per \> $swap_warn`

#如果当前交换分区使用超过80%（即剩余小于20%，上面的返回值等于0），立即发告警
if (($swap_now == 0)); then
echo "$IP服务器swap交换分区只剩下 $swap_free M 未使用，剩余不足20%，使用率已经超过80%，请及时处理。" 
fi

fi
 
}
cpuuse
