#!/bin/bash
set -e
set -o xtrace
temp_dir=`mktemp`; rm -rf $temp_dir; mkdir -p $temp_dir
TOPDIR=$(cd $(dirname "$0") && pwd)

function _create_mac_file(){
mac_temp=$TOPDIR/mac_temp
cat <<"EOF" >$mac_temp
# This file was automatically generated by the /lib/udev/write_net_rules
# program, run by the persistent-net-generator.rules rules file.
#
# You can modify it, as long as you keep each rule on a single
# line, and change only the value of the NAME= key.
# PCI device 0x10ec:0x8139 (8139cp)
SUBSYSTEM=="net", ACTION=="add", DRIVERS=="?*", ATTR{address}=="%MAC%", ATTR{type}=="1", KERNEL=="eth*", NAME="eth0"
SUBSYSTEM=="net", ACTION=="add", DRIVERS=="?*", ATTR{address}=="%MAC2%", ATTR{type}=="1", KERNEL=="eth*", NAME="eth1"
EOF
}

function _create_net_file(){
net_temp=$TOPDIR/net_temp
cat <<"EOF">$net_temp
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet dhcp

auto eth1
iface eth1 inet static
    address 10.111.102.%IP%
    netmask 255.255.255.0
    broadcast 10.111.102.255
    gateway 10.111.102.1
EOF
}

function __mount_qcow2_disk(){
    modprobe nbd  max_part=63
    qemu-nbd -c /dev/nbd0 $TOPDIR/vmos-$1.qcow2
    sleep 1
    kpartx -a /dev/nbd0
    sleep 1
    mount /dev/mapper/nbd0p1 $temp_dir
}

function __umount_qcow2_disk(){
    umount $temp_dir
    qemu-nbd -d /dev/nbd0
}

function _create_image(){
    ip=$1; mac=$2; mac2=$3; HOST_NAME=vmos-${ip}
    qemu-img create -f raw vmos-$ip.raw 40G
}

function create_xml(){
    ip=$1
    xml_file=vmos-${ip}.xml
    cp -rf $TOPDIR/vmos.xml $xml_file
    sed -i "s,%VM_NAME%,vmos-${i},g" $xml_file
    UUID=`uuidgen`
    sed -i "s,%UUID%,$UUID,g" $xml_file
    MAC="fa:95:$(dd if=/dev/urandom count=1 2>/dev/null \
           | md5sum | sed 's/^\(..\)\(..\)\(..\)\(..\).*$/\1:\2:\3:\4/')"
    sed -i "s,%MAC%,$MAC,g" $xml_file
    MAC2="52:54:$(dd if=/dev/urandom count=1 2>/dev/null \
           | md5sum | sed 's/^\(..\)\(..\)\(..\)\(..\).*$/\1:\2:\3:\4/')"
    sed -i "s,%MAC2%,$MAC2,g" $xml_file
    MAC3="52:54:$(dd if=/dev/urandom count=1 2>/dev/null \
           | md5sum | sed 's/^\(..\)\(..\)\(..\)\(..\).*$/\1:\2:\3:\4/')"
    sed -i "s,%MAC3%,$MAC3,g" $xml_file    
    isopath=`ls $TOPDIR/*.iso`
    sed -i "s,%ISO_PATH%,$isopath,g" $xml_file
_create_image $ip 
    
    IMAGE_PATH="${TOPDIR}/vmos-${i}.raw"
    sed -i "s,%IMAGE_PATH%,$IMAGE_PATH,g" $xml_file
}

_create_mac_file
for i in 244 ; do
    create_xml $i
    virsh define vmos-${i}.xml
    virsh start vmos-${i}
done

set +o xtrace
